<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Configurations>Debug;DebugAuto;DebugHC;Release</Configurations>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <AssemblyTitle>buildThisFirst.Properties</AssemblyTitle>
    <Product>buildThisFirst.Properties</Product>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'DebugAuto'">
    <VersionStrategy>AutoIncrement</VersionStrategy>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'DebugHC'">
    <VersionStrategy>HardCoded</VersionStrategy>
    <VersionMajor>4</VersionMajor>
    <VersionMinor>1</VersionMinor>
    <VersionBuild>0</VersionBuild>
    <VersionRevision>1</VersionRevision>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Debug')) And '$(Platform)' == 'x64'">
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\x64\Release\</OutputPath>
    <DocumentationFile>bin\x64\Release\buildThisFirst.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Debug')) And '$(Platform)' == 'AnyCPU'">
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineTrace>true</DefineTrace>
    <DocumentationFile>bin\x64\Release\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugAuto|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugAuto|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugHC|x64'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\x64\DebugHC\</OutputPath>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DebugHC|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>bin\DebugHC\</OutputPath>
    <DocumentationFile>bin\x64\Debug\buildThisFirst.xml</DocumentationFile>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Handlebars.Net" Version="2.1.6" />
    <PackageReference Include="Microsoft.TestApi" Version="0.6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="4.6.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>
</Project>
