<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <MyType>Windows</MyType>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;DebugAuto;DebugHC;Release</Configurations>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\UnitTests.xml</DocumentationFile>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\UnitTests.xml</DocumentationFile>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DocumentationFile>bin\x64\Debug\UnitTests.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DocumentationFile>bin\x64\Release\UnitTests.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcCoreMgd, Version=24.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\_libs\AutoCAD 2024\AcCoreMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcCui">
      <HintPath>..\_libs\AutoCAD 2024\AcCui.dll</HintPath>
    </Reference>
    <Reference Include="AcDbMgd, Version=24.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\_libs\AutoCAD 2024\AcDbMgd.dll</HintPath>
    </Reference>
    <Reference Include="acdbmgdbrep">
      <HintPath>..\_libs\AutoCAD 2024\acdbmgdbrep.dll</HintPath>
    </Reference>
    <Reference Include="AcDx">
      <HintPath>..\_libs\AutoCAD 2024\AcDx.dll</HintPath>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcMr">
      <HintPath>..\_libs\AutoCAD 2024\AcMr.dll</HintPath>
    </Reference>
    <Reference Include="AcSeamless">
      <HintPath>..\_libs\AutoCAD 2024\AcSeamless.dll</HintPath>
    </Reference>
    <Reference Include="AcTcMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcTcMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcWindows">
      <HintPath>..\_libs\AutoCAD 2024\AcWindows.dll</HintPath>
    </Reference>
    <Reference Include="AdUIMgd">
      <HintPath>..\_libs\AutoCAD 2024\AdUIMgd.dll</HintPath>
    </Reference>
    <Reference Include="AdUiPalettes">
      <HintPath>..\_libs\AutoCAD 2024\AdUiPalettes.dll</HintPath>
    </Reference>
    <Reference Include="AdWindows, Version=3.0.2.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\_libs\AutoCAD 2024\AdWindows.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.AutoCAD.Interop">
      <HintPath>..\_libs\AutoCAD 2024\Autodesk.AutoCAD.Interop.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="Autodesk.AutoCAD.Interop.Common">
      <HintPath>..\_libs\AutoCAD 2024\Autodesk.AutoCAD.Interop.Common.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.2" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
    <Import Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\cadwiki.DllReloader\cadwiki.DllReloader.csproj" />
    <ProjectReference Include="..\cadwiki.FileStore\cadwiki.FileStore.csproj" />
    <ProjectReference Include="..\cadwiki.NetUtils\cadwiki.NetUtils.csproj" />
    <ProjectReference Include="..\cadwiki.NUnitTestRunner\cadwiki.NUnitTestRunner.csproj" />
  </ItemGroup>
</Project>