<Project Sdk="Microsoft.NET.Sdk">
  <UsingTask AssemblyFile="..\packages\MSBuild.Extension.Pack.1.9.1\tools\net40\MSBuild.ExtensionPack.dll" TaskName="AssemblyInfo" />
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <BuildRoot>$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), build.root))</BuildRoot>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;DebugAuto;DebugHC;Release</Configurations>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <OptionExplicit>On</OptionExplicit>
    <OptionCompare>Binary</OptionCompare>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
  </PropertyGroup>
  <Target Name="ExecutePowerShellScriptToCreateNetloadScripts" AfterTargets="CopyAssembliesToTempFolder">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="thisProjectAssemblyIdentities" />
    </GetAssemblyIdentity>
    <PropertyGroup>
      <CurrentDateTime>$([System.DateTime]::Now.ToString("yyyy_MM_dd_HH_mm_ss"))</CurrentDateTime>
      <TempFolderPath>$([System.IO.Path]::Combine($([System.IO.Path]::GetTempPath()), "cadwiki.TestPlugin", %(thisProjectAssemblyIdentities.Version)))\</TempFolderPath>
      <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
      <ScriptPath>$(ProjectDir)BuildNetloadScript.ps1</ScriptPath>
    </PropertyGroup>
    <MakeDir Directories="$(TempFolderPath)" />
    <Exec Command="PowerShell -NoProfile -ExecutionPolicy Unrestricted -File &quot;$(ScriptPath)&quot; &quot;$(TempFolderPath)&quot;" />
  </Target>
  <Target Name="CopyUnloadDll" AfterTargets="Build">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="thisProjectAssemblyIdentities" />
    </GetAssemblyIdentity>
    <PropertyGroup>
      <CurrentDateTime>$([System.DateTime]::Now.ToString("yyyy_MM_dd_HH_mm_ss"))</CurrentDateTime>
      <TempFolderPath>$([System.IO.Path]::Combine($([System.IO.Path]::GetTempPath()), "cadwiki.TestPlugin", %(thisProjectAssemblyIdentities.Version)))\</TempFolderPath>
      <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
    </PropertyGroup>
    <MakeDir Directories="$(TempFolderPath)" />
    <ItemGroup>
      <DllFiles Include="$(BuildRoot)\_libs\AutoCAD 2024\cadwiki.AcRemoveCmdGroup.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(DllFiles)" DestinationFolder="$(TempFolderPath)" />
    <Message Importance="High" Text="Unload copied to Temp folder: $(TempFolderPath)" />
  </Target>
  <Target Name="CopyAssembliesToTempFolder" AfterTargets="Build">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="thisProjectAssemblyIdentities" />
    </GetAssemblyIdentity>
    <PropertyGroup>
      <CurrentDateTime>$([System.DateTime]::Now.ToString("yyyy_MM_dd_HH_mm_ss"))</CurrentDateTime>
      <TempFolderPath>$([System.IO.Path]::Combine($([System.IO.Path]::GetTempPath()), "cadwiki.TestPlugin", %(thisProjectAssemblyIdentities.Version)))\</TempFolderPath>
      <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.vb</DefaultItemExcludes>
      <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
      <Reference Include="Microsoft.VisualBasic" />
      <OutputFiles Include="$(TargetPath)" />
    </ItemGroup>
    <MakeDir Directories="$(TempFolderPath)" />
    <ItemGroup>
      <FilesToCopy Include="$(TargetDir)**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(FilesToCopy)" DestinationFolder="$(TempFolderPath)">
      <Output TaskParameter="CopiedFiles" ItemName="CopiedOutputFiles" />
    </Copy>
    <Message Importance="High" Text="Files copied to Temp folder: $(TempFolderPath)" />
  </Target>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\cadwiki.AC.TestPlugin.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\cadwiki.AC.TestPlugin.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DocumentationFile>bin\x64\Debug\cadwiki.AC.TestPlugin.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <DocumentationFile>bin\x64\Release\cadwiki.AC.TestPlugin.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AcCoreMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcCoreMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcCui">
      <HintPath>..\_libs\AutoCAD 2024\AcCui.dll</HintPath>
    </Reference>
    <Reference Include="AcDbMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcDbMgd.dll</HintPath>
    </Reference>
    <Reference Include="acdbmgdbrep">
      <HintPath>..\_libs\AutoCAD 2024\acdbmgdbrep.dll</HintPath>
    </Reference>
    <Reference Include="AcDx">
      <HintPath>..\_libs\AutoCAD 2024\AcDx.dll</HintPath>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcMr">
      <HintPath>..\_libs\AutoCAD 2024\AcMr.dll</HintPath>
    </Reference>
    <Reference Include="AcSeamless">
      <HintPath>..\_libs\AutoCAD 2024\AcSeamless.dll</HintPath>
    </Reference>
    <Reference Include="AcTcMgd">
      <HintPath>..\_libs\AutoCAD 2024\AcTcMgd.dll</HintPath>
    </Reference>
    <Reference Include="AcWindows">
      <HintPath>..\_libs\AutoCAD 2024\AcWindows.dll</HintPath>
    </Reference>
    <Reference Include="AdUIMgd">
      <HintPath>..\_libs\AutoCAD 2024\AdUIMgd.dll</HintPath>
    </Reference>
    <Reference Include="AdUiPalettes">
      <HintPath>..\_libs\AutoCAD 2024\AdUiPalettes.dll</HintPath>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>..\_libs\AutoCAD 2024\AdWindows.dll</HintPath>
    </Reference>
    <PackageReference Include="MSBuild.Extension.Pack" Version="1.9.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Import Include="Microsoft.VisualBasic" />
    <Import Include="System" />
    <Import Include="System.Collections" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Data" />
    <Import Include="System.Diagnostics" />
    <Import Include="System.Linq" />
    <Import Include="System.Xml.Linq" />
    <Import Include="System.Threading.Tasks" />
    <Import Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\cadwiki.AC\cadwiki.AC.csproj" />
    <ProjectReference Include="..\cadwiki.DllReloader\cadwiki.DllReloader.csproj" />
    <ProjectReference Include="..\cadwiki.FileStore\cadwiki.FileStore.csproj" />
    <ProjectReference Include="..\cadwiki.NetUtils\cadwiki.NetUtils.csproj" />
    <ProjectReference Include="..\cadwiki.NUnitTestRunner\cadwiki.NUnitTestRunner.csproj" />
    <ProjectReference Include="..\cadwiki.WpfUi\cadwiki.WpfUi.csproj" />
  </ItemGroup>
</Project>
