<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;DebugAuto;DebugHC;Release</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\cadwiki.NetUtils\cadwiki.NetUtils.csproj" />
    <ProjectReference Include="..\cadwiki.WpfLibrary\cadwiki.WpfLibrary.csproj" />
    <PackageReference Include="Caliburn.Micro" Version="5.0.258" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>
